language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx

script:
  - dotnet build
  - dotnet restore
  - cd DotNetEssentials.Tests
  - dotnet test
