language: csharp
dist: trusty
mono: none
dotnet: 2.0.3

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx

install:
  - dotnet restore

script:
  - dotnet build
  - cd cd DotNetEssentials.Tests
  - dotnet test
