language: csharp
solution: DotNetEssentials.sln
mono: none
dotnet: 2.0.3

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx

script:
  - cd DotNetEssentials.Tests
  - dotnet test
